apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: xanho-backend
  name: xanho-backend
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: xanho-backend
        actorSystemName: xanho-backend
    spec:
      serviceAccountName: xanho-backend-sa
      automountServiceAccountToken: false
      containers:
        - name: xanho-backend
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          ports:
            - name: remoting
              containerPort: 25520
              protocol: TCP
            - name: management
              containerPort: 8558
              protocol: TCP
            - name: app
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: varlog
              mountPath: /var/log
          readinessProbe:
            httpGet:
              path: /ready
              port: management
          livenessProbe:
            httpGet:
              path: /alive
              port: management
          resources:
            requests:
              memory: 1024Mi
            limits:
              memory: 1024Mi
          env:
            - name: AKKA_CLUSTER_BOOTSTRAP_SERVICE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: "metadata.labels['app']"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: REQUIRED_CONTACT_POINT_NR
              value: "2"
            - name: GOOGLE_PROJECT_ID
              value: "xanho-151422"
        - name: log-out
          image: busybox
          args: [ /bin/sh, -c, 'tail -n+1 -f /var/log/xanho-backend.log' ]
          volumeMounts:
            - name: varlog
              mountPath: /var/log
      volumes:
        - name: varlog
          emptyDir: { }
