apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: xanho-backend
  name: xanho-backend
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: xanho-backend
        actorSystemName: xanho-backend
    spec:
      serviceAccountName: xanho-backend-sa
      automountServiceAccountToken: true
      containers:
        - name: xanho-backend
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          ports:
            - name: remoting
              containerPort: 25520
              protocol: TCP
            - name: management
              containerPort: 8558
              protocol: TCP
            - name: app
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /ready
              port: management
            periodSeconds: 10
            failureThreshold: 10
            initialDelaySeconds: 20
          livenessProbe:
            httpGet:
              path: /alive
              port: management
            periodSeconds: 10
            failureThreshold: 10
            initialDelaySeconds: 20
          resources:
            requests:
              memory: 768Mi
            limits:
              memory: 768Mi
          env:
            - name: AKKA_CLUSTER_BOOTSTRAP_SERVICE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: "metadata.labels['app']"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: REQUIRED_CONTACT_POINT_NR
              value: "2"
            - name: GOOGLE_PROJECT_ID
              value: "xanho-151422"
