apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: xanho-backend
  name: xanho-backend
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: xanho-backend
    spec:
      serviceAccountName: xanho-backend-sa
      automountServiceAccountToken: false
      containers:
        - name: xanho-backend
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          ports:
            - containerPort: 8080
            - containerPort: 2551
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1024Mi