apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: xanho-backend-internal
  namespace: xanho-backend
spec:
  secretName: xanho-backend-internal
  duration: 2160h
  renewBefore: 360h
  subject:
    organizations:
    - xanho
  commonName: backend.xanho.org
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
  - backend.xanho.org
  issuerRef:
    name: xanho-selfsigned-issuer
    kind: Issuer