apiVersion: v1
kind: Service
metadata:
  namespace: xanho-backend
  name: xanho-backend
  annotations:
    service.alpha.kubernetes.io/app-protocols: '{"app":"HTTP2"}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  ports:
    - name: healthcheck
      port: 80
      targetPort: 8080
    - name: app
      port: 443
      targetPort: 8443
  selector:
    app: xanho-backend
