apiVersion: v1
kind: Service
metadata:
  namespace: xanho-backend
  name: xanho-backend
spec:
  type: NodePort
  ports:
    - name: healthcheck
      port: 80
      targetPort: 8080
    - name: app
      port: 8081
      targetPort: 8081
  selector:
    app: xanho-backend
