apiVersion: v1
kind: Service
metadata:
  namespace: xanho-backend
  name: xanho-backend-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: xanho-backend