apiVersion: v1
kind: Service
metadata:
  namespace: xanho-backend
  name: xanho-backend
  annotations:
    service.alpha.kubernetes.io/app-protocols: '{"app":"HTTP2", "healthcheck": "HTTP"}'
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "xanho-backend-healthcheck"}'
spec:
  type: NodePort
  ports:
    - name: healthcheck
      port: 8081
      targetPort: 8081
    - name: app
      port: 443
      targetPort: 8443
  selector:
    app: xanho-backend
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: xanho-backend-healthcheck
  namespace: xanho-backend
spec:
  healthCheck:
    checkIntervalSec: 15
    port: 8081
    type: HTTP