kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: xanho-backend
  name: pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: xanho-backend
  name: read-pods
subjects:
  - kind: ServiceAccount
    name: xanho-backend-sa
    namespace: xanho-backend
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io