name: xanho-backend Build

on:
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: xanho
  GKE_ZONE: us-central1-c
  IMAGE: xanho-backend

jobs:
  build:
    name: Setup, Build, and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - run: |-
          gcloud --quiet auth configure-docker

      - name: SbtBuild
        working-directory: ./xanho-backend
        run: |-
          sbt serviceKubernetes/docker:stage

      - name: DockerBuild
        working-directory: ./xanho-backend/serviceKubernetes/target/docker/stage
        run: |-
          docker build \
            --tag "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            .
      - name: Publish
        working-directory: ./xanho-backend/serviceKubernetes/target/docker/stage
        run: |-
          docker push "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"
