name: xanho-frontend Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Setup, Build, Upload
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: beta
      - run: flutter config --enable-web
      - run: flutter pub get
        working-directory: ./frontend
      - run: flutter test
        working-directory: ./frontend
      - run: flutter build web
        working-directory: ./frontend
      - name: Upload Web Dist
        uses: actions/upload-artifact@v2
        with:
          name: web-dist
          path: frontend/build/web/
          if-no-files-found: error
