name: xanho-backend Deploy

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'GitHub SHA/Tag from a Build job'
        required: true

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: xanho
  GKE_ZONE: us-central1-c
  DEPLOYMENT_NAME: xanho-backend
  IMAGE: xanho-backend

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - run: |-
          gcloud --quiet auth configure-docker

      - run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

      - name: Set up Kustomize
        working-directory: ./xanho-backend/deploy/kubernetes
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv3.8.5/kustomize_v3.8.5_linux_amd64.tar.gz
          tar -xvf kustomize_v3.8.5_linux_amd64.tar.gz
          rm kustomize_v3.8.5_linux_amd64.tar.gz
          chmod u+x ./kustomize

      - name: Deploy
        working-directory: ./xanho-backend/deploy/kubernetes
        run: |-
          ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/$PROJECT_ID/$IMAGE:${{ github.event.inputs.tag }}
          ./kustomize build . | kubectl apply -n xanho-backend -f -
          kubectl rollout status -n xanho-backend deployment/$DEPLOYMENT_NAME
          kubectl get services -n xanho-backend -o wide
