name: xanho-backend Build and Deploy

on:
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: xanho
  GKE_ZONE: us-central1-c
  DEPLOYMENT_NAME: xanho-backend
  IMAGE: xanho-backend

jobs:
  build:
    name: Setup, Build, and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Checkout
        uses: actions/checkout@v2

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - run: |-
          gcloud --quiet auth configure-docker

      - name: SbtBuild
        working-directory: ./xanho-backend
        run: |-
          sbt serviceKubernetes/docker:stage

      - name: DockerBuild
        working-directory: ./xanho-backend/serviceKubernetes/target/docker/stage
        run: |-
          docker build \
            --tag "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            .
      - name: Publish
        working-directory: ./xanho-backend/serviceKubernetes/target/docker/stage
        run: |-
          docker push "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - run: |-
          gcloud --quiet auth configure-docker

      - run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

      - name: Set up Kustomize
        working-directory: ./xanho-backend/deploy/kubernetes
        run: |-
          curl -sfLo kustomize_v3.8.5_linux_amd64.tar.gz https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv3.8.5/kustomize_v3.8.5_linux_amd64.tar.gz
          tar -xvf kustomize_v3.8.5_linux_amd64.tar.gz
          rm kustomize_v3.8.5_linux_amd64.tar.gz
          chmod u+x ./kustomize

      - name: Deploy
        working-directory: ./xanho-backend/deploy/kubernetes
        run: |-
          ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/$PROJECT_ID/$IMAGE:${{ github.event.inputs.tag }}
          ./kustomize build . | kubectl apply -n xanho-backend -f -
          kubectl rollout status -n xanho-backend deployment/$DEPLOYMENT_NAME
          kubectl get services -n xanho-backend -o wide
