name: xanho-frontend Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Setup, Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: dev
      - run: flutter config --enable-web
      - run: flutter pub get
        working-directory: ./frontend
      - run: flutter test --platform chrome
        working-directory: ./frontend
      - run: flutter build web
        working-directory: ./frontend
