name: xanho-frontend Build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'GitHub SHA/Tag from a Build job'
        required: true

jobs:
  build:
    name: Setup, Build, Upload
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: ${{ github.event.inputs.tag }}
          path: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          PROJECT_ID: ${{ secrets.GKE_PROJECT }}
